// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenSeaWebApi.Data;

#nullable disable

namespace OpenSeaWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("company_id")
                        .HasColumnType("integer");

                    b.Property<string>("contact")
                        .HasColumnType("text");

                    b.Property<byte[]>("image")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("image_small")
                        .HasColumnType("bytea");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("observations")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.AppUserConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("AppUser_id")
                        .HasColumnType("integer");

                    b.Property<bool>("isDarkTheme")
                        .HasColumnType("boolean");

                    b.Property<int>("itemsPerPage")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("AppUser_id")
                        .IsUnique();

                    b.ToTable("db_configUser");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomAsset", b =>
                {
                    b.Property<int>("primary_key_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("primary_key_Id"));

                    b.Property<string>("AnimationOriginalUrl")
                        .HasColumnType("text");

                    b.Property<string>("AnimationUrl")
                        .HasColumnType("text");

                    b.Property<int?>("AssetContractprimary_key_Id")
                        .HasColumnType("integer");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("text");

                    b.Property<int?>("Collectionprimary_key_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Decimals")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalLink")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ImageOriginalUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImagePreviewUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumSales")
                        .HasColumnType("integer");

                    b.Property<int?>("Ownerprimary_key_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Permalink")
                        .HasColumnType("text");

                    b.Property<string>("TokenId")
                        .HasColumnType("text");

                    b.Property<string>("TokenMetadata")
                        .HasColumnType("text");

                    b.HasKey("primary_key_Id");

                    b.HasIndex("AssetContractprimary_key_Id");

                    b.HasIndex("Collectionprimary_key_Id");

                    b.HasIndex("Ownerprimary_key_Id");

                    b.ToTable("CustomAsset");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomAssetContract", b =>
                {
                    b.Property<int>("primary_key_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("primary_key_Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AssetContractType")
                        .HasColumnType("text");

                    b.Property<int>("BuyerFeeBasisPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultToFiat")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DevBuyerFeeBasisPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DevSellerFeeBasisPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalLink")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NftVersion")
                        .HasColumnType("text");

                    b.Property<bool>("OnlyProxiedTransfers")
                        .HasColumnType("boolean");

                    b.Property<int>("OpenseaBuyerFeeBasisPoints")
                        .HasColumnType("integer");

                    b.Property<int>("OpenseaSellerFeeBasisPoints")
                        .HasColumnType("integer");

                    b.Property<string>("OpenseaVersion")
                        .HasColumnType("text");

                    b.Property<int?>("Owner")
                        .HasColumnType("integer");

                    b.Property<string>("PayoutAddress")
                        .HasColumnType("text");

                    b.Property<string>("SchemaName")
                        .HasColumnType("text");

                    b.Property<int>("SellerFeeBasisPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("TotalSupply")
                        .HasColumnType("text");

                    b.HasKey("primary_key_Id");

                    b.ToTable("CustomAssetContract");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomAssetEvent", b =>
                {
                    b.Property<int>("primary_key_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("primary_key_Id"));

                    b.Property<int?>("Assetprimary_key_Id")
                        .HasColumnType("integer");

                    b.Property<string>("CollectionSlug")
                        .HasColumnType("text");

                    b.Property<string>("ContractAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Quantity")
                        .HasColumnType("text");

                    b.Property<string>("TotalPrice")
                        .HasColumnType("text");

                    b.HasKey("primary_key_Id");

                    b.HasIndex("Assetprimary_key_Id");

                    b.ToTable("db_AssetEvent");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomCollection", b =>
                {
                    b.Property<int>("primary_key_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("primary_key_Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ChatUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultToFiat")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DevBuyerFeeBasisPoints")
                        .HasColumnType("text");

                    b.Property<string>("DevSellerFeeBasisPoints")
                        .HasColumnType("text");

                    b.Property<string>("DiscordUrl")
                        .HasColumnType("text");

                    b.Property<int?>("DisplayDataprimary_key_Id")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<string>("FeaturedImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstagramUsername")
                        .HasColumnType("text");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubjectToWhitelist")
                        .HasColumnType("boolean");

                    b.Property<string>("LargeImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("MediumUsername")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("OnlyProxiedTransfers")
                        .HasColumnType("boolean");

                    b.Property<string>("OpenseaBuyerFeeBasisPoints")
                        .HasColumnType("text");

                    b.Property<string>("OpenseaSellerFeeBasisPoints")
                        .HasColumnType("text");

                    b.Property<string>("PayoutAddress")
                        .HasColumnType("text");

                    b.Property<bool>("RequireEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("SafelistRequestStatus")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<string>("TelegramUrl")
                        .HasColumnType("text");

                    b.Property<string>("TwitterUsername")
                        .HasColumnType("text");

                    b.Property<string>("WikiUrl")
                        .HasColumnType("text");

                    b.HasKey("primary_key_Id");

                    b.HasIndex("DisplayDataprimary_key_Id");

                    b.ToTable("db_Collection");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomDisplayData", b =>
                {
                    b.Property<int>("primary_key_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("primary_key_Id"));

                    b.Property<string>("CardDisplayStyle")
                        .HasColumnType("text");

                    b.Property<string>("Images")
                        .HasColumnType("text");

                    b.HasKey("primary_key_Id");

                    b.ToTable("CustomDisplayData");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomOwner", b =>
                {
                    b.Property<int>("primary_key_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("primary_key_Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Config")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileImgUrl")
                        .HasColumnType("text");

                    b.Property<int?>("Userprimary_key_Id")
                        .HasColumnType("integer");

                    b.HasKey("primary_key_Id");

                    b.HasIndex("Userprimary_key_Id");

                    b.ToTable("CustomOwner");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomUser", b =>
                {
                    b.Property<int>("primary_key_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("primary_key_Id"));

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("primary_key_Id");

                    b.ToTable("CustomUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("OpenSeaWebApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("OpenSeaWebApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenSeaWebApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("OpenSeaWebApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.AppUserConfig", b =>
                {
                    b.HasOne("OpenSeaWebApi.Models.AppUser", "AppUser")
                        .WithOne("UserConfigs")
                        .HasForeignKey("OpenSeaWebApi.Models.AppUserConfig", "AppUser_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomAsset", b =>
                {
                    b.HasOne("OpenSeaWebApi.Models.CustomAssetContract", "AssetContract")
                        .WithMany()
                        .HasForeignKey("AssetContractprimary_key_Id");

                    b.HasOne("OpenSeaWebApi.Models.CustomCollection", "Collection")
                        .WithMany()
                        .HasForeignKey("Collectionprimary_key_Id");

                    b.HasOne("OpenSeaWebApi.Models.CustomOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("Ownerprimary_key_Id");

                    b.Navigation("AssetContract");

                    b.Navigation("Collection");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomAssetEvent", b =>
                {
                    b.HasOne("OpenSeaWebApi.Models.CustomAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("Assetprimary_key_Id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomCollection", b =>
                {
                    b.HasOne("OpenSeaWebApi.Models.CustomDisplayData", "DisplayData")
                        .WithMany()
                        .HasForeignKey("DisplayDataprimary_key_Id");

                    b.Navigation("DisplayData");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.CustomOwner", b =>
                {
                    b.HasOne("OpenSeaWebApi.Models.CustomUser", "User")
                        .WithMany()
                        .HasForeignKey("Userprimary_key_Id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenSeaWebApi.Models.AppUser", b =>
                {
                    b.Navigation("UserConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
